In [21]:
import torch
import einops

In [5]:
batch_size = 2

In [9]:
counts = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

In [10]:
indices = torch.tensor([
    [0, 1],
    [0, 1],
    [0, 1],
    [0, 1]
])

In [11]:
trigger = torch.tensor([[[ True],
          [False],
          [False],
          [ True]],
 
         [[ True],
          [ True],
          [False],
          [ True]]])

In [12]:
res = torch.where(trigger, 0 , torch.gather(counts, -1, indices).reshape(batch_size, -1, 1))

In [13]:
res

tensor([[[ 0],
         [ 2],
         [ 4],
         [ 0]],

        [[ 0],
         [ 0],
         [10],
         [ 0]]])

In [16]:
counts.unsqueeze(0).expand(batch_size, -1, -1)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [19]:
indices.shape, indices, indices.T.reshape(batch_size, -1, 1)

(torch.Size([4, 2]),
 tensor([[0, 1],
         [0, 1],
         [0, 1],
         [0, 1]]),
 tensor([[[0],
          [0],
          [0],
          [0]],
 
         [[1],
          [1],
          [1],
          [1]]]))

In [20]:
torch.scatter(counts.unsqueeze(0).expand(batch_size, -1, -1), -1, indices.T.reshape(batch_size, -1, 1), res)

tensor([[[ 0,  2,  3],
         [ 2,  5,  6],
         [ 4,  8,  9],
         [ 0, 11, 12]],

        [[ 1,  0,  3],
         [ 4,  0,  6],
         [ 7, 10,  9],
         [10,  0, 12]]])

In [22]:
einops.reduce(torch.scatter(counts.unsqueeze(0).expand(batch_size, -1, -1), -1, indices.T.reshape(batch_size, -1, 1), res), 'b n c -> n c', 'sum')

tensor([[ 1,  2,  6],
        [ 6,  5, 12],
        [11, 18, 18],
        [10, 11, 24]])